Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 70
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	7	aggregate_data_summary
	77	align
	1	all
	77	create_blocks
	77	merge_fastq
	239
Resources before job selection: {'_cores': 70, '_nodes': 9223372036854775807}
Ready jobs (77):
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
Selected jobs (70):
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775737}

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip2/barcode29/0/fastq_files.lst
    jobid: 31
    wildcards: chip=Chip2, native=barcode29, block=0


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode29/*.fastq.gz             | head -n 100 > results/Chip2/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode29/0/fastq_files.lst
        rm -f results/Chip2/barcode29/0/fastq_files.lst.temp
        

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip1/barcode25/8/fastq_files.lst
    jobid: 29
    wildcards: chip=Chip1, native=barcode25, block=8


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp
        

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip1/barcode31/3/fastq_files.lst
    jobid: 14
    wildcards: chip=Chip1, native=barcode31, block=3


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode31/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/3/fastq_files.lst
        rm -f results/Chip1/barcode31/3/fastq_files.lst.temp
        

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip2/barcode27/4/fastq_files.lst
    jobid: 45
    wildcards: chip=Chip2, native=barcode27, block=4


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode27/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/4/fastq_files.lst
        rm -f results/Chip2/barcode27/4/fastq_files.lst.temp
        

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip1/barcode30/9/fastq_files.lst
    jobid: 10
    wildcards: chip=Chip1, native=barcode30, block=9


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp
        
[Tue Apr 22 12:58:43 2025]
Finished job 31.
1 of 239 steps (0.42%) done

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip2/barcode29/5/fastq_files.lst
    jobid: 36
    wildcards: chip=Chip2, native=barcode29, block=5


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode29/*.fastq.gz             | head -n 100 > results/Chip2/barcode29/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode29/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip2/barcode29/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode29/5/fastq_files.lst
        rm -f results/Chip2/barcode29/5/fastq_files.lst.temp
        

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
    jobid: 236
    wildcards: chip=Chip2, native=barcode27, block=<function <lambda> at 0x7fe8bd7859d0>


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp
        

[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip1/barcode31/2/fastq_files.lst
    jobid: 13
    wildcards: chip=Chip1, native=barcode31, block=2
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode27/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/4/fastq_files.lst
        rm -f results/Chip2/barcode27/4/fastq_files.lst.temp' returned non-zero exit status 141.


[Tue Apr 22 12:58:43 2025]
[Tue Apr 22 12:58:43 2025]

        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip1/barcode31/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/2/fastq_files.lst
        rm -f results/Chip1/barcode31/2/fastq_files.lst.temp
        
Finished job 36.
Error in rule create_blocks:
2 of 239 steps (0.84%) done
    jobid: 45
    output: results/Chip2/barcode27/4/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode27/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/4/fastq_files.lst
        rm -f results/Chip2/barcode27/4/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


[Tue Apr 22 12:58:43 2025]
rule create_blocks:
    output: results/Chip2/barcode28/9/fastq_files.lst
    jobid: 70
    wildcards: chip=Chip2, native=barcode28, block=9


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode28/*.fastq.gz             | head -n 100 > results/Chip2/barcode28/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode28/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip2/barcode28/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode28/9/fastq_files.lst
        rm -f results/Chip2/barcode28/9/fastq_files.lst.temp
        
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode27/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/4/fastq_files.lst
        rm -f results/Chip2/barcode27/4/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode27/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/4/fastq_files.lst
        rm -f results/Chip2/barcode27/4/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' returned non-zero exit status 1.

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip2/barcode27/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/4/fastq_files.lst
        rm -f results/Chip2/barcode27/4/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Tue Apr 22 12:58:43 2025]
Job failed, going on with independent jobs.
Error in rule create_blocks:

    jobid: 236
[Tue Apr 22 12:58:43 2025]
    output: results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
rule create_blocks:
    output: results/Chip1/barcode30/0/fastq_files.lst
    jobid: 1
    wildcards: chip=Chip1, native=barcode30, block=0
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)



        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode30/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/0/fastq_files.lst
        rm -f results/Chip1/barcode30/0/fastq_files.lst.temp
        
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' returned non-zero exit status 1.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz             | head -n 100 > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip2/barcode27/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' returned non-zero exit status 1.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
[Tue Apr 22 12:58:43 2025]
Finished job 70.
3 of 239 steps (1%) done
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode31/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/3/fastq_files.lst
        rm -f results/Chip1/barcode31/3/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 12:58:43 2025]
Error in rule create_blocks:
    jobid: 14
    output: results/Chip1/barcode31/3/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode31/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/3/fastq_files.lst
        rm -f results/Chip1/barcode31/3/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode31/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/3/fastq_files.lst
        rm -f results/Chip1/barcode31/3/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode31/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/3/fastq_files.lst
        rm -f results/Chip1/barcode31/3/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode31/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/3/fastq_files.lst
        rm -f results/Chip1/barcode31/3/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 12:58:43 2025]
Error in rule create_blocks:
    jobid: 10
    output: results/Chip1/barcode30/9/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode30/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/9/fastq_files.lst
        rm -f results/Chip1/barcode30/9/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode30/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/0/fastq_files.lst
        rm -f results/Chip1/barcode30/0/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 12:58:43 2025]
Error in rule create_blocks:
    jobid: 1
    output: results/Chip1/barcode30/0/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode30/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/0/fastq_files.lst
        rm -f results/Chip1/barcode30/0/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode30/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/0/fastq_files.lst
        rm -f results/Chip1/barcode30/0/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode30/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/0/fastq_files.lst
        rm -f results/Chip1/barcode30/0/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz             | head -n 100 > results/Chip1/barcode30/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode30/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/0/fastq_files.lst
        rm -f results/Chip1/barcode30/0/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip1/barcode31/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/2/fastq_files.lst
        rm -f results/Chip1/barcode31/2/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 12:58:43 2025]
Error in rule create_blocks:
    jobid: 13
    output: results/Chip1/barcode31/2/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip1/barcode31/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/2/fastq_files.lst
        rm -f results/Chip1/barcode31/2/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip1/barcode31/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/2/fastq_files.lst
        rm -f results/Chip1/barcode31/2/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip1/barcode31/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/2/fastq_files.lst
        rm -f results/Chip1/barcode31/2/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip1/barcode31/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/2/fastq_files.lst
        rm -f results/Chip1/barcode31/2/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' returned non-zero exit status 141.

[Tue Apr 22 12:58:43 2025]
Error in rule create_blocks:
    jobid: 29
    output: results/Chip1/barcode25/8/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' returned non-zero exit status 141.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode25/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/8/fastq_files.lst
        rm -f results/Chip1/barcode25/8/fastq_files.lst.temp' returned non-zero exit status 141.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.

[Tue Apr 22 12:58:44 2025]
rule create_blocks:
    output: results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
    jobid: 234
    wildcards: chip=Chip1, native=barcode25, block=<function <lambda> at 0x7fe8bd7859d0>


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp
        

[Tue Apr 22 12:58:44 2025]
rule create_blocks:
    output: results/Chip1/barcode31/7/fastq_files.lst
    jobid: 18
    wildcards: chip=Chip1, native=barcode31, block=7


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode31/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/7/fastq_files.lst
        rm -f results/Chip1/barcode31/7/fastq_files.lst.temp
        

[Tue Apr 22 12:58:44 2025]
Terminating processes on user request, this might take some time.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

[Tue Apr 22 12:58:44 2025]
Error in rule create_blocks:
    jobid: 234
    output: results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz             | head -n 100 > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (<function <lambda> at 0x7fe8bd7859d0>+1)))

        head -n $nhead results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst
        rm -f results/Chip1/barcode25/<function <lambda> at 0x7fe8bd7859d0>/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode31/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/7/fastq_files.lst
        rm -f results/Chip1/barcode31/7/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

[Tue Apr 22 12:58:44 2025]
Error in rule create_blocks:
    jobid: 18
    output: results/Chip1/barcode31/7/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode31/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/7/fastq_files.lst
        rm -f results/Chip1/barcode31/7/fastq_files.lst.temp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 125, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode31/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/7/fastq_files.lst
        rm -f results/Chip1/barcode31/7/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode31/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/7/fastq_files.lst
        rm -f results/Chip1/barcode31/7/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks

RuleException:
CalledProcessError in line 96 of /data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz             | head -n 100 > results/Chip1/barcode31/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode31/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/7/fastq_files.lst
        rm -f results/Chip1/barcode31/7/fastq_files.lst.temp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/2025-04-15_HT27-2025-04-11_Run1/snakefile", line 96, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/scheduler.py", line 374, in schedule
    self.run(job)
  File "/usr/lib/python3/dist-packages/snakemake/scheduler.py", line 389, in run
    self.get_executor(job).run(
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 356, in run
    super()._run(job)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 174, in _run
    super()._run(job)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 106, in _run
    self.printjob(job)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 112, in printjob
    job.log_info(skip_dynamic=True)
  File "/usr/lib/python3/dist-packages/snakemake/jobs.py", line 896, in log_info
    logger.job_info(
  File "/usr/lib/python3/dist-packages/snakemake/logging.py", line 217, in job_info
    self.handler(msg)
  File "/usr/lib/python3/dist-packages/snakemake/logging.py", line 166, in handler
    handler(msg)
  File "/usr/lib/python3/dist-packages/snakemake/logging.py", line 308, in text_handler
    timestamp()
  File "/usr/lib/python3/dist-packages/snakemake/logging.py", line 301, in timestamp
    self.logger.info(indent("[{}]".format(time.asctime())))
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1187, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/__init__.py", line 561, in snakemake
    success = workflow.execute(
  File "/usr/lib/python3/dist-packages/snakemake/workflow.py", line 850, in execute
    success = scheduler.schedule()
  File "/usr/lib/python3/dist-packages/snakemake/scheduler.py", line 379, in schedule
    self._executor.cancel()
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 466, in cancel
    self.pool.shutdown()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

Cancelling snakemake on user request.
unlocking
removing lock
removing lock
removed all locks
