Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 40
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	8	aggregate_data_summary
	110	align
	1	all
	110	create_blocks
	110	merge_fastq
	339
Resources before job selection: {'_cores': 40, '_nodes': 9223372036854775807}
Ready jobs (110):
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
Selected jobs (40):
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
	create_blocks
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775767}

[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip2/barcode26/0/fastq_files.lst
    jobid: 51
    wildcards: chip=Chip2, native=barcode26, block=0


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode26/*.fastq.gz > results/Chip2/barcode26/0/fastq_files.lst.tmp
        head -n 100 results/Chip2/barcode26/0/fastq_files.lst.tmp > results/Chip2/barcode26/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode26/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip2/barcode26/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode26/0/fastq_files.lst
        rm -f results/Chip2/barcode26/0/fastq_files.lst.temp results/Chip2/barcode26/0/fastq_files.lst.tmp
        

[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip1/barcode27/1/fastq_files.lst
    jobid: 310
    wildcards: chip=Chip1, native=barcode27, block=1


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/1/fastq_files.lst.tmp > results/Chip1/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/1/fastq_files.lst
        rm -f results/Chip1/barcode27/1/fastq_files.lst.temp results/Chip1/barcode27/1/fastq_files.lst.tmp
        

[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip1/barcode26/7/fastq_files.lst
    jobid: 326
    wildcards: chip=Chip1, native=barcode26, block=7


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/7/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/7/fastq_files.lst.tmp > results/Chip1/barcode26/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode26/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/7/fastq_files.lst
        rm -f results/Chip1/barcode26/7/fastq_files.lst.temp results/Chip1/barcode26/7/fastq_files.lst.tmp
        

[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip1/barcode30/2/fastq_files.lst
    jobid: 3
    wildcards: chip=Chip1, native=barcode30, block=2


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode30/*.fastq.gz > results/Chip1/barcode30/2/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode30/2/fastq_files.lst.tmp > results/Chip1/barcode30/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode30/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip1/barcode30/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode30/2/fastq_files.lst
        rm -f results/Chip1/barcode30/2/fastq_files.lst.temp results/Chip1/barcode30/2/fastq_files.lst.tmp
        

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/1/fastq_files.lst.tmp > results/Chip1/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/1/fastq_files.lst
        rm -f results/Chip1/barcode27/1/fastq_files.lst.temp results/Chip1/barcode27/1/fastq_files.lst.tmp' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/7/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/7/fastq_files.lst.tmp > results/Chip1/barcode26/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode26/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/7/fastq_files.lst
        rm -f results/Chip1/barcode26/7/fastq_files.lst.temp results/Chip1/barcode26/7/fastq_files.lst.tmp' returned non-zero exit status 1.

[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip2/barcode27/2/fastq_files.lst
    jobid: 43
    wildcards: chip=Chip2, native=barcode27, block=2
[Tue Apr 22 22:38:29 2025]
[Tue Apr 22 22:38:29 2025]

Error in rule create_blocks:
Error in rule create_blocks:

        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode27/*.fastq.gz > results/Chip2/barcode27/2/fastq_files.lst.tmp
        head -n 100 results/Chip2/barcode27/2/fastq_files.lst.tmp > results/Chip2/barcode27/2/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode27/2/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (2+1)))

        head -n $nhead results/Chip2/barcode27/2/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode27/2/fastq_files.lst
        rm -f results/Chip2/barcode27/2/fastq_files.lst.temp results/Chip2/barcode27/2/fastq_files.lst.tmp
        
    jobid: 326
    jobid: 310
    output: results/Chip1/barcode26/7/fastq_files.lst
    output: results/Chip1/barcode27/1/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/7/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/7/fastq_files.lst.tmp > results/Chip1/barcode26/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode26/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/7/fastq_files.lst
        rm -f results/Chip1/barcode26/7/fastq_files.lst.temp results/Chip1/barcode26/7/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/1/fastq_files.lst.tmp > results/Chip1/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/1/fastq_files.lst
        rm -f results/Chip1/barcode27/1/fastq_files.lst.temp results/Chip1/barcode27/1/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/7/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/7/fastq_files.lst.tmp > results/Chip1/barcode26/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode26/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/7/fastq_files.lst
        rm -f results/Chip1/barcode26/7/fastq_files.lst.temp results/Chip1/barcode26/7/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/7/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/7/fastq_files.lst.tmp > results/Chip1/barcode26/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode26/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/7/fastq_files.lst
        rm -f results/Chip1/barcode26/7/fastq_files.lst.temp results/Chip1/barcode26/7/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/1/fastq_files.lst.tmp > results/Chip1/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/1/fastq_files.lst
        rm -f results/Chip1/barcode27/1/fastq_files.lst.temp results/Chip1/barcode27/1/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/1/fastq_files.lst.tmp > results/Chip1/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/1/fastq_files.lst
        rm -f results/Chip1/barcode27/1/fastq_files.lst.temp results/Chip1/barcode27/1/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/7/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/7/fastq_files.lst.tmp > results/Chip1/barcode26/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip1/barcode26/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/7/fastq_files.lst
        rm -f results/Chip1/barcode26/7/fastq_files.lst.temp results/Chip1/barcode26/7/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/1/fastq_files.lst.tmp > results/Chip1/barcode27/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode27/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/1/fastq_files.lst
        rm -f results/Chip1/barcode27/1/fastq_files.lst.temp results/Chip1/barcode27/1/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

Job failed, going on with independent jobs.
[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip1/barcode28/5/fastq_files.lst
    jobid: 334
    wildcards: chip=Chip1, native=barcode28, block=5


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/5/fastq_files.lst.tmp > results/Chip1/barcode28/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode28/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/5/fastq_files.lst
        rm -f results/Chip1/barcode28/5/fastq_files.lst.temp results/Chip1/barcode28/5/fastq_files.lst.tmp
        
Job failed, going on with independent jobs.

[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip1/barcode28/8/fastq_files.lst
    jobid: 337
    wildcards: chip=Chip1, native=barcode28, block=8


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/8/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/8/fastq_files.lst.tmp > results/Chip1/barcode28/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode28/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/8/fastq_files.lst
        rm -f results/Chip1/barcode28/8/fastq_files.lst.temp results/Chip1/barcode28/8/fastq_files.lst.tmp
        
[Tue Apr 22 22:38:29 2025]
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/5/fastq_files.lst.tmp > results/Chip1/barcode28/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode28/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/5/fastq_files.lst
        rm -f results/Chip1/barcode28/5/fastq_files.lst.temp results/Chip1/barcode28/5/fastq_files.lst.tmp' returned non-zero exit status 1.


Finished job 51.
[Tue Apr 22 22:38:29 2025]
1 of 339 steps (0.29%) done
rule create_blocks:
    output: results/Chip2/barcode29/7/fastq_files.lst
    jobid: 38
    wildcards: chip=Chip2, native=barcode29, block=7


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode29/*.fastq.gz > results/Chip2/barcode29/7/fastq_files.lst.tmp
        head -n 100 results/Chip2/barcode29/7/fastq_files.lst.tmp > results/Chip2/barcode29/7/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode29/7/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (7+1)))

        head -n $nhead results/Chip2/barcode29/7/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode29/7/fastq_files.lst
        rm -f results/Chip2/barcode29/7/fastq_files.lst.temp results/Chip2/barcode29/7/fastq_files.lst.tmp
        
[Tue Apr 22 22:38:29 2025]
Error in rule create_blocks:
    jobid: 334
    output: results/Chip1/barcode28/5/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/5/fastq_files.lst.tmp > results/Chip1/barcode28/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode28/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/5/fastq_files.lst
        rm -f results/Chip1/barcode28/5/fastq_files.lst.temp results/Chip1/barcode28/5/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/5/fastq_files.lst.tmp > results/Chip1/barcode28/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode28/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/5/fastq_files.lst
        rm -f results/Chip1/barcode28/5/fastq_files.lst.temp results/Chip1/barcode28/5/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/5/fastq_files.lst.tmp > results/Chip1/barcode28/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode28/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/5/fastq_files.lst
        rm -f results/Chip1/barcode28/5/fastq_files.lst.temp results/Chip1/barcode28/5/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/8/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/8/fastq_files.lst.tmp > results/Chip1/barcode28/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode28/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/8/fastq_files.lst
        rm -f results/Chip1/barcode28/8/fastq_files.lst.temp results/Chip1/barcode28/8/fastq_files.lst.tmp' returned non-zero exit status 1.


RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/5/fastq_files.lst.tmp > results/Chip1/barcode28/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode28/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/5/fastq_files.lst
        rm -f results/Chip1/barcode28/5/fastq_files.lst.temp results/Chip1/barcode28/5/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Tue Apr 22 22:38:29 2025]
[Tue Apr 22 22:38:29 2025]
rule create_blocks:
    output: results/Chip1/barcode29/0/fastq_files.lst
    jobid: 299
    wildcards: chip=Chip1, native=barcode29, block=0
Error in rule create_blocks:

    jobid: 337

        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode29/*.fastq.gz > results/Chip1/barcode29/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode29/0/fastq_files.lst.tmp > results/Chip1/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode29/0/fastq_files.lst
        rm -f results/Chip1/barcode29/0/fastq_files.lst.temp results/Chip1/barcode29/0/fastq_files.lst.tmp
        
    output: results/Chip1/barcode28/8/fastq_files.lst
[Tue Apr 22 22:38:29 2025]
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/8/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/8/fastq_files.lst.tmp > results/Chip1/barcode28/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode28/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/8/fastq_files.lst
        rm -f results/Chip1/barcode28/8/fastq_files.lst.temp results/Chip1/barcode28/8/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Finished job 43.

2 of 339 steps (0.59%) done
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/8/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/8/fastq_files.lst.tmp > results/Chip1/barcode28/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode28/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/8/fastq_files.lst
        rm -f results/Chip1/barcode28/8/fastq_files.lst.temp results/Chip1/barcode28/8/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/8/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/8/fastq_files.lst.tmp > results/Chip1/barcode28/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode28/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/8/fastq_files.lst
        rm -f results/Chip1/barcode28/8/fastq_files.lst.temp results/Chip1/barcode28/8/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks


Job failed, going on with independent jobs.
[Tue Apr 22 22:38:29 2025]
RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/8/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/8/fastq_files.lst.tmp > results/Chip1/barcode28/8/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/8/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (8+1)))

        head -n $nhead results/Chip1/barcode28/8/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/8/fastq_files.lst
        rm -f results/Chip1/barcode28/8/fastq_files.lst.temp results/Chip1/barcode28/8/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
rule create_blocks:
    output: results/Chip1/barcode28/4/fastq_files.lst
    jobid: 333
    wildcards: chip=Chip1, native=barcode28, block=4


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/4/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/4/fastq_files.lst.tmp > results/Chip1/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip1/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/4/fastq_files.lst
        rm -f results/Chip1/barcode28/4/fastq_files.lst.temp results/Chip1/barcode28/4/fastq_files.lst.tmp
        
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode29/*.fastq.gz > results/Chip1/barcode29/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode29/0/fastq_files.lst.tmp > results/Chip1/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode29/0/fastq_files.lst
        rm -f results/Chip1/barcode29/0/fastq_files.lst.temp results/Chip1/barcode29/0/fastq_files.lst.tmp' returned non-zero exit status 1.

[Tue Apr 22 22:38:29 2025]
[Tue Apr 22 22:38:29 2025]
Finished job 38.
Error in rule create_blocks:
3 of 339 steps (0.88%) done
    jobid: 299
    output: results/Chip1/barcode29/0/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode29/*.fastq.gz > results/Chip1/barcode29/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode29/0/fastq_files.lst.tmp > results/Chip1/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode29/0/fastq_files.lst
        rm -f results/Chip1/barcode29/0/fastq_files.lst.temp results/Chip1/barcode29/0/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode29/*.fastq.gz > results/Chip1/barcode29/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode29/0/fastq_files.lst.tmp > results/Chip1/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode29/0/fastq_files.lst
        rm -f results/Chip1/barcode29/0/fastq_files.lst.temp results/Chip1/barcode29/0/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode29/*.fastq.gz > results/Chip1/barcode29/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode29/0/fastq_files.lst.tmp > results/Chip1/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode29/0/fastq_files.lst
        rm -f results/Chip1/barcode29/0/fastq_files.lst.temp results/Chip1/barcode29/0/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/4/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/4/fastq_files.lst.tmp > results/Chip1/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip1/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/4/fastq_files.lst
        rm -f results/Chip1/barcode28/4/fastq_files.lst.temp results/Chip1/barcode28/4/fastq_files.lst.tmp' returned non-zero exit status 1.

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode29/*.fastq.gz > results/Chip1/barcode29/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode29/0/fastq_files.lst.tmp > results/Chip1/barcode29/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode29/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode29/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode29/0/fastq_files.lst
        rm -f results/Chip1/barcode29/0/fastq_files.lst.temp results/Chip1/barcode29/0/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Tue Apr 22 22:38:29 2025]
Error in rule create_blocks:
Job failed, going on with independent jobs.
    jobid: 333
    output: results/Chip1/barcode28/4/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/4/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/4/fastq_files.lst.tmp > results/Chip1/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip1/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/4/fastq_files.lst
        rm -f results/Chip1/barcode28/4/fastq_files.lst.temp results/Chip1/barcode28/4/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/4/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/4/fastq_files.lst.tmp > results/Chip1/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip1/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/4/fastq_files.lst
        rm -f results/Chip1/barcode28/4/fastq_files.lst.temp results/Chip1/barcode28/4/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/4/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/4/fastq_files.lst.tmp > results/Chip1/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip1/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/4/fastq_files.lst
        rm -f results/Chip1/barcode28/4/fastq_files.lst.temp results/Chip1/barcode28/4/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/4/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/4/fastq_files.lst.tmp > results/Chip1/barcode28/4/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/4/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (4+1)))

        head -n $nhead results/Chip1/barcode28/4/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/4/fastq_files.lst
        rm -f results/Chip1/barcode28/4/fastq_files.lst.temp results/Chip1/barcode28/4/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
[Tue Apr 22 22:38:30 2025]
Finished job 3.
4 of 339 steps (1%) done

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip1/barcode26/3/fastq_files.lst
    jobid: 322
    wildcards: chip=Chip1, native=barcode26, block=3


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/3/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/3/fastq_files.lst.tmp > results/Chip1/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/3/fastq_files.lst
        rm -f results/Chip1/barcode26/3/fastq_files.lst.temp results/Chip1/barcode26/3/fastq_files.lst.tmp
        

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip1/barcode28/6/fastq_files.lst
    jobid: 335
    wildcards: chip=Chip1, native=barcode28, block=6


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/6/fastq_files.lst.tmp > results/Chip1/barcode28/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode28/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/6/fastq_files.lst
        rm -f results/Chip1/barcode28/6/fastq_files.lst.temp results/Chip1/barcode28/6/fastq_files.lst.tmp
        

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip2/barcode29/3/fastq_files.lst
    jobid: 34
    wildcards: chip=Chip2, native=barcode29, block=3
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/3/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/3/fastq_files.lst.tmp > results/Chip1/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/3/fastq_files.lst
        rm -f results/Chip1/barcode26/3/fastq_files.lst.temp results/Chip1/barcode26/3/fastq_files.lst.tmp' returned non-zero exit status 1.



        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode29/*.fastq.gz > results/Chip2/barcode29/3/fastq_files.lst.tmp
        head -n 100 results/Chip2/barcode29/3/fastq_files.lst.tmp > results/Chip2/barcode29/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode29/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip2/barcode29/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode29/3/fastq_files.lst
        rm -f results/Chip2/barcode29/3/fastq_files.lst.temp results/Chip2/barcode29/3/fastq_files.lst.tmp
        
[Tue Apr 22 22:38:30 2025]
Error in rule create_blocks:
    jobid: 322
    output: results/Chip1/barcode26/3/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/3/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/3/fastq_files.lst.tmp > results/Chip1/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/3/fastq_files.lst
        rm -f results/Chip1/barcode26/3/fastq_files.lst.temp results/Chip1/barcode26/3/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/3/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/3/fastq_files.lst.tmp > results/Chip1/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/3/fastq_files.lst
        rm -f results/Chip1/barcode26/3/fastq_files.lst.temp results/Chip1/barcode26/3/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/3/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/3/fastq_files.lst.tmp > results/Chip1/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/3/fastq_files.lst
        rm -f results/Chip1/barcode26/3/fastq_files.lst.temp results/Chip1/barcode26/3/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks


Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/6/fastq_files.lst.tmp > results/Chip1/barcode28/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode28/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/6/fastq_files.lst
        rm -f results/Chip1/barcode28/6/fastq_files.lst.temp results/Chip1/barcode28/6/fastq_files.lst.tmp' returned non-zero exit status 1.

[Tue Apr 22 22:38:30 2025]
RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/3/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/3/fastq_files.lst.tmp > results/Chip1/barcode26/3/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/3/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (3+1)))

        head -n $nhead results/Chip1/barcode26/3/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/3/fastq_files.lst
        rm -f results/Chip1/barcode26/3/fastq_files.lst.temp results/Chip1/barcode26/3/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
rule create_blocks:
    output: results/Chip1/barcode31/0/fastq_files.lst
    jobid: 11
    wildcards: chip=Chip1, native=barcode31, block=0


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode31/*.fastq.gz > results/Chip1/barcode31/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode31/0/fastq_files.lst.tmp > results/Chip1/barcode31/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode31/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode31/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode31/0/fastq_files.lst
        rm -f results/Chip1/barcode31/0/fastq_files.lst.temp results/Chip1/barcode31/0/fastq_files.lst.tmp
        
[Tue Apr 22 22:38:30 2025]
Job failed, going on with independent jobs.
Error in rule create_blocks:
    jobid: 335
    output: results/Chip1/barcode28/6/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/6/fastq_files.lst.tmp > results/Chip1/barcode28/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode28/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/6/fastq_files.lst
        rm -f results/Chip1/barcode28/6/fastq_files.lst.temp results/Chip1/barcode28/6/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/6/fastq_files.lst.tmp > results/Chip1/barcode28/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode28/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/6/fastq_files.lst
        rm -f results/Chip1/barcode28/6/fastq_files.lst.temp results/Chip1/barcode28/6/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/6/fastq_files.lst.tmp > results/Chip1/barcode28/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode28/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/6/fastq_files.lst
        rm -f results/Chip1/barcode28/6/fastq_files.lst.temp results/Chip1/barcode28/6/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/6/fastq_files.lst.tmp > results/Chip1/barcode28/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode28/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/6/fastq_files.lst
        rm -f results/Chip1/barcode28/6/fastq_files.lst.temp results/Chip1/barcode28/6/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip1/barcode27/6/fastq_files.lst
    jobid: 315
    wildcards: chip=Chip1, native=barcode27, block=6


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/6/fastq_files.lst.tmp > results/Chip1/barcode27/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode27/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/6/fastq_files.lst
        rm -f results/Chip1/barcode27/6/fastq_files.lst.temp results/Chip1/barcode27/6/fastq_files.lst.tmp
        
[Tue Apr 22 22:38:30 2025]
Finished job 34.
5 of 339 steps (1%) done

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip1/barcode28/1/fastq_files.lst
    jobid: 330
    wildcards: chip=Chip1, native=barcode28, block=1


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/1/fastq_files.lst.tmp > results/Chip1/barcode28/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode28/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/1/fastq_files.lst
        rm -f results/Chip1/barcode28/1/fastq_files.lst.temp results/Chip1/barcode28/1/fastq_files.lst.tmp
        

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/6/fastq_files.lst.tmp > results/Chip1/barcode27/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode27/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/6/fastq_files.lst
        rm -f results/Chip1/barcode27/6/fastq_files.lst.temp results/Chip1/barcode27/6/fastq_files.lst.tmp' returned non-zero exit status 1.

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip1/barcode25/0/fastq_files.lst
    jobid: 21
    wildcards: chip=Chip1, native=barcode25, block=0


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz > results/Chip1/barcode25/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode25/0/fastq_files.lst.tmp > results/Chip1/barcode25/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode25/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/0/fastq_files.lst
        rm -f results/Chip1/barcode25/0/fastq_files.lst.temp results/Chip1/barcode25/0/fastq_files.lst.tmp
        
[Tue Apr 22 22:38:30 2025]
Error in rule create_blocks:
    jobid: 315
    output: results/Chip1/barcode27/6/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/6/fastq_files.lst.tmp > results/Chip1/barcode27/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode27/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/6/fastq_files.lst
        rm -f results/Chip1/barcode27/6/fastq_files.lst.temp results/Chip1/barcode27/6/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/6/fastq_files.lst.tmp > results/Chip1/barcode27/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode27/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/6/fastq_files.lst
        rm -f results/Chip1/barcode27/6/fastq_files.lst.temp results/Chip1/barcode27/6/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/6/fastq_files.lst.tmp > results/Chip1/barcode27/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode27/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/6/fastq_files.lst
        rm -f results/Chip1/barcode27/6/fastq_files.lst.temp results/Chip1/barcode27/6/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/6/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/6/fastq_files.lst.tmp > results/Chip1/barcode27/6/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/6/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (6+1)))

        head -n $nhead results/Chip1/barcode27/6/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/6/fastq_files.lst
        rm -f results/Chip1/barcode27/6/fastq_files.lst.temp results/Chip1/barcode27/6/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/1/fastq_files.lst.tmp > results/Chip1/barcode28/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode28/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/1/fastq_files.lst
        rm -f results/Chip1/barcode28/1/fastq_files.lst.temp results/Chip1/barcode28/1/fastq_files.lst.tmp' returned non-zero exit status 1.


Job failed, going on with independent jobs.
[Tue Apr 22 22:38:30 2025]
[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip2/barcode29/9/fastq_files.lst
    jobid: 40
    wildcards: chip=Chip2, native=barcode29, block=9
Error in rule create_blocks:

    jobid: 330

        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip2/*/fastq_pass/barcode29/*.fastq.gz > results/Chip2/barcode29/9/fastq_files.lst.tmp
        head -n 100 results/Chip2/barcode29/9/fastq_files.lst.tmp > results/Chip2/barcode29/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip2/barcode29/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip2/barcode29/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip2/barcode29/9/fastq_files.lst
        rm -f results/Chip2/barcode29/9/fastq_files.lst.temp results/Chip2/barcode29/9/fastq_files.lst.tmp
        
    output: results/Chip1/barcode28/1/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/1/fastq_files.lst.tmp > results/Chip1/barcode28/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode28/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/1/fastq_files.lst
        rm -f results/Chip1/barcode28/1/fastq_files.lst.temp results/Chip1/barcode28/1/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/1/fastq_files.lst.tmp > results/Chip1/barcode28/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode28/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/1/fastq_files.lst
        rm -f results/Chip1/barcode28/1/fastq_files.lst.temp results/Chip1/barcode28/1/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/1/fastq_files.lst.tmp > results/Chip1/barcode28/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode28/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/1/fastq_files.lst
        rm -f results/Chip1/barcode28/1/fastq_files.lst.temp results/Chip1/barcode28/1/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode28/*.fastq.gz > results/Chip1/barcode28/1/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode28/1/fastq_files.lst.tmp > results/Chip1/barcode28/1/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode28/1/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (1+1)))

        head -n $nhead results/Chip1/barcode28/1/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode28/1/fastq_files.lst
        rm -f results/Chip1/barcode28/1/fastq_files.lst.temp results/Chip1/barcode28/1/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip1/barcode26/9/fastq_files.lst
    jobid: 328
    wildcards: chip=Chip1, native=barcode26, block=9


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/9/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/9/fastq_files.lst.tmp > results/Chip1/barcode26/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode26/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/9/fastq_files.lst
        rm -f results/Chip1/barcode26/9/fastq_files.lst.temp results/Chip1/barcode26/9/fastq_files.lst.tmp
        

[Tue Apr 22 22:38:30 2025]
rule create_blocks:
    output: results/Chip1/barcode27/5/fastq_files.lst
    jobid: 314
    wildcards: chip=Chip1, native=barcode27, block=5


        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/5/fastq_files.lst.tmp > results/Chip1/barcode27/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode27/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/5/fastq_files.lst
        rm -f results/Chip1/barcode27/5/fastq_files.lst.temp results/Chip1/barcode27/5/fastq_files.lst.tmp
        
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/9/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/9/fastq_files.lst.tmp > results/Chip1/barcode26/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode26/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/9/fastq_files.lst
        rm -f results/Chip1/barcode26/9/fastq_files.lst.temp results/Chip1/barcode26/9/fastq_files.lst.tmp' returned non-zero exit status 1.

[Tue Apr 22 22:38:30 2025]
Finished job 40.
[Tue Apr 22 22:38:30 2025]
6 of 339 steps (2%) done
Error in rule create_blocks:
    jobid: 328
    output: results/Chip1/barcode26/9/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/9/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/9/fastq_files.lst.tmp > results/Chip1/barcode26/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode26/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/9/fastq_files.lst
        rm -f results/Chip1/barcode26/9/fastq_files.lst.temp results/Chip1/barcode26/9/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/9/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/9/fastq_files.lst.tmp > results/Chip1/barcode26/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode26/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/9/fastq_files.lst
        rm -f results/Chip1/barcode26/9/fastq_files.lst.temp results/Chip1/barcode26/9/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/9/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/9/fastq_files.lst.tmp > results/Chip1/barcode26/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode26/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/9/fastq_files.lst
        rm -f results/Chip1/barcode26/9/fastq_files.lst.temp results/Chip1/barcode26/9/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode26/*.fastq.gz > results/Chip1/barcode26/9/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode26/9/fastq_files.lst.tmp > results/Chip1/barcode26/9/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode26/9/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (9+1)))

        head -n $nhead results/Chip1/barcode26/9/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode26/9/fastq_files.lst
        rm -f results/Chip1/barcode26/9/fastq_files.lst.temp results/Chip1/barcode26/9/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/5/fastq_files.lst.tmp > results/Chip1/barcode27/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode27/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/5/fastq_files.lst
        rm -f results/Chip1/barcode27/5/fastq_files.lst.temp results/Chip1/barcode27/5/fastq_files.lst.tmp' returned non-zero exit status 1.

[Tue Apr 22 22:38:30 2025]
Error in rule create_blocks:
    jobid: 314
    output: results/Chip1/barcode27/5/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/5/fastq_files.lst.tmp > results/Chip1/barcode27/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode27/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/5/fastq_files.lst
        rm -f results/Chip1/barcode27/5/fastq_files.lst.temp results/Chip1/barcode27/5/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/5/fastq_files.lst.tmp > results/Chip1/barcode27/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode27/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/5/fastq_files.lst
        rm -f results/Chip1/barcode27/5/fastq_files.lst.temp results/Chip1/barcode27/5/fastq_files.lst.tmp' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/5/fastq_files.lst.tmp > results/Chip1/barcode27/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode27/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/5/fastq_files.lst
        rm -f results/Chip1/barcode27/5/fastq_files.lst.temp results/Chip1/barcode27/5/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode27/*.fastq.gz > results/Chip1/barcode27/5/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode27/5/fastq_files.lst.tmp > results/Chip1/barcode27/5/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode27/5/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (5+1)))

        head -n $nhead results/Chip1/barcode27/5/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode27/5/fastq_files.lst
        rm -f results/Chip1/barcode27/5/fastq_files.lst.temp results/Chip1/barcode27/5/fastq_files.lst.tmp' returned non-zero exit status 1.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
[Tue Apr 22 22:38:31 2025]
Finished job 11.
7 of 339 steps (2%) done
Terminating processes on user request, this might take some time.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz > results/Chip1/barcode25/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode25/0/fastq_files.lst.tmp > results/Chip1/barcode25/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode25/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/0/fastq_files.lst
        rm -f results/Chip1/barcode25/0/fastq_files.lst.temp results/Chip1/barcode25/0/fastq_files.lst.tmp' died with <Signals.SIGINT: 2>.

[Tue Apr 22 22:38:31 2025]
Error in rule create_blocks:
    jobid: 21
    output: results/Chip1/barcode25/0/fastq_files.lst
    shell:
        
        realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz > results/Chip1/barcode25/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode25/0/fastq_files.lst.tmp > results/Chip1/barcode25/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode25/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/0/fastq_files.lst
        rm -f results/Chip1/barcode25/0/fastq_files.lst.temp results/Chip1/barcode25/0/fastq_files.lst.tmp
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2071, in run_wrapper
    run(
  File "/data/Analysis/working/snakefile", line 134, in __rule_create_blocks
    input:
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 162, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz > results/Chip1/barcode25/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode25/0/fastq_files.lst.tmp > results/Chip1/barcode25/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode25/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/0/fastq_files.lst
        rm -f results/Chip1/barcode25/0/fastq_files.lst.temp results/Chip1/barcode25/0/fastq_files.lst.tmp' died with <Signals.SIGINT: 2>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 472, in _callback
    raise ex
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 458, in cached_or_run
    run_func(*args)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 2101, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz > results/Chip1/barcode25/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode25/0/fastq_files.lst.tmp > results/Chip1/barcode25/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode25/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/0/fastq_files.lst
        rm -f results/Chip1/barcode25/0/fastq_files.lst.temp results/Chip1/barcode25/0/fastq_files.lst.tmp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks

RuleException:
CalledProcessError in line 105 of /data/Analysis/working/snakefile:
Command 'set -euo pipefail;  realpath /data/data-transfer_KCRB/2025-04-15_HT27-2025-04-11_Run1/Chip1/*/fastq_pass/barcode25/*.fastq.gz > results/Chip1/barcode25/0/fastq_files.lst.tmp
        head -n 100 results/Chip1/barcode25/0/fastq_files.lst.tmp > results/Chip1/barcode25/0/fastq_files.lst.temp

        nfiles=$(wc -l < results/Chip1/barcode25/0/fastq_files.lst.temp)
        nfiles_per_block=$((nfiles / 10))
        nhead=$((nfiles_per_block * (0+1)))

        head -n $nhead results/Chip1/barcode25/0/fastq_files.lst.temp | tail -n $nfiles_per_block > results/Chip1/barcode25/0/fastq_files.lst
        rm -f results/Chip1/barcode25/0/fastq_files.lst.temp results/Chip1/barcode25/0/fastq_files.lst.tmp' died with <Signals.SIGINT: 2>.
  File "/data/Analysis/working/snakefile", line 105, in __rule_create_blocks
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Job failed, going on with independent jobs.
Complete log: /data/Analysis/working/.snakemake/log/2025-04-22T223829.650883.snakemake.log
unlocking
removing lock
removing lock
removed all locks
